/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreatmentsRouteImport } from './routes/treatments'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookAppointmentRouteImport } from './routes/book-appointment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConcernsIndexRouteImport } from './routes/concerns.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ConcernsSlugRouteImport } from './routes/concerns.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminShellRouteRouteImport } from './routes/admin/_shell/route'
import { Route as AdminShellSettingsRouteImport } from './routes/admin/_shell/settings'
import { Route as AdminShellDashboardRouteImport } from './routes/admin/_shell/dashboard'
import { Route as AdminShellCustomersRouteImport } from './routes/admin/_shell/customers'
import { Route as AdminShellCalendarRouteImport } from './routes/admin/_shell/calendar'
import { Route as AdminShellAppointmentsRouteImport } from './routes/admin/_shell/appointments'

const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAppointmentRoute = BookAppointmentRouteImport.update({
  id: '/book-appointment',
  path: '/book-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcernsIndexRoute = ConcernsIndexRouteImport.update({
  id: '/concerns/',
  path: '/concerns/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ConcernsSlugRoute = ConcernsSlugRouteImport.update({
  id: '/concerns/$slug',
  path: '/concerns/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShellRouteRoute = AdminShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShellSettingsRoute = AdminShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminShellRouteRoute,
} as any)
const AdminShellDashboardRoute = AdminShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminShellRouteRoute,
} as any)
const AdminShellCustomersRoute = AdminShellCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminShellRouteRoute,
} as any)
const AdminShellCalendarRoute = AdminShellCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminShellRouteRoute,
} as any)
const AdminShellAppointmentsRoute = AdminShellAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminShellRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/gallery': typeof GalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/treatments': typeof TreatmentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/concerns/$slug': typeof ConcernsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/concerns/': typeof ConcernsIndexRoute
  '/admin/appointments': typeof AdminShellAppointmentsRoute
  '/admin/calendar': typeof AdminShellCalendarRoute
  '/admin/customers': typeof AdminShellCustomersRoute
  '/admin/dashboard': typeof AdminShellDashboardRoute
  '/admin/settings': typeof AdminShellSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/gallery': typeof GalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/treatments': typeof TreatmentsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/concerns/$slug': typeof ConcernsSlugRoute
  '/concerns': typeof ConcernsIndexRoute
  '/admin/appointments': typeof AdminShellAppointmentsRoute
  '/admin/calendar': typeof AdminShellCalendarRoute
  '/admin/customers': typeof AdminShellCustomersRoute
  '/admin/dashboard': typeof AdminShellDashboardRoute
  '/admin/settings': typeof AdminShellSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/gallery': typeof GalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/treatments': typeof TreatmentsRoute
  '/admin/_shell': typeof AdminShellRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/concerns/$slug': typeof ConcernsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/concerns/': typeof ConcernsIndexRoute
  '/admin/_shell/appointments': typeof AdminShellAppointmentsRoute
  '/admin/_shell/calendar': typeof AdminShellCalendarRoute
  '/admin/_shell/customers': typeof AdminShellCustomersRoute
  '/admin/_shell/dashboard': typeof AdminShellDashboardRoute
  '/admin/_shell/settings': typeof AdminShellSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/book-appointment'
    | '/contact'
    | '/doctors'
    | '/gallery'
    | '/sitemap.xml'
    | '/treatments'
    | '/admin/login'
    | '/concerns/$slug'
    | '/admin/'
    | '/concerns/'
    | '/admin/appointments'
    | '/admin/calendar'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book-appointment'
    | '/contact'
    | '/doctors'
    | '/gallery'
    | '/sitemap.xml'
    | '/treatments'
    | '/admin'
    | '/admin/login'
    | '/concerns/$slug'
    | '/concerns'
    | '/admin/appointments'
    | '/admin/calendar'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/book-appointment'
    | '/contact'
    | '/doctors'
    | '/gallery'
    | '/sitemap.xml'
    | '/treatments'
    | '/admin/_shell'
    | '/admin/login'
    | '/concerns/$slug'
    | '/admin/'
    | '/concerns/'
    | '/admin/_shell/appointments'
    | '/admin/_shell/calendar'
    | '/admin/_shell/customers'
    | '/admin/_shell/dashboard'
    | '/admin/_shell/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BookAppointmentRoute: typeof BookAppointmentRoute
  ContactRoute: typeof ContactRoute
  DoctorsRoute: typeof DoctorsRoute
  GalleryRoute: typeof GalleryRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TreatmentsRoute: typeof TreatmentsRoute
  ConcernsSlugRoute: typeof ConcernsSlugRoute
  ConcernsIndexRoute: typeof ConcernsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-appointment': {
      id: '/book-appointment'
      path: '/book-appointment'
      fullPath: '/book-appointment'
      preLoaderRoute: typeof BookAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concerns/': {
      id: '/concerns/'
      path: '/concerns'
      fullPath: '/concerns/'
      preLoaderRoute: typeof ConcernsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/concerns/$slug': {
      id: '/concerns/$slug'
      path: '/concerns/$slug'
      fullPath: '/concerns/$slug'
      preLoaderRoute: typeof ConcernsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/_shell': {
      id: '/admin/_shell'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminShellRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/_shell/settings': {
      id: '/admin/_shell/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminShellSettingsRouteImport
      parentRoute: typeof AdminShellRouteRoute
    }
    '/admin/_shell/dashboard': {
      id: '/admin/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminShellDashboardRouteImport
      parentRoute: typeof AdminShellRouteRoute
    }
    '/admin/_shell/customers': {
      id: '/admin/_shell/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminShellCustomersRouteImport
      parentRoute: typeof AdminShellRouteRoute
    }
    '/admin/_shell/calendar': {
      id: '/admin/_shell/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminShellCalendarRouteImport
      parentRoute: typeof AdminShellRouteRoute
    }
    '/admin/_shell/appointments': {
      id: '/admin/_shell/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminShellAppointmentsRouteImport
      parentRoute: typeof AdminShellRouteRoute
    }
  }
}

interface AdminShellRouteRouteChildren {
  AdminShellAppointmentsRoute: typeof AdminShellAppointmentsRoute
  AdminShellCalendarRoute: typeof AdminShellCalendarRoute
  AdminShellCustomersRoute: typeof AdminShellCustomersRoute
  AdminShellDashboardRoute: typeof AdminShellDashboardRoute
  AdminShellSettingsRoute: typeof AdminShellSettingsRoute
}

const AdminShellRouteRouteChildren: AdminShellRouteRouteChildren = {
  AdminShellAppointmentsRoute: AdminShellAppointmentsRoute,
  AdminShellCalendarRoute: AdminShellCalendarRoute,
  AdminShellCustomersRoute: AdminShellCustomersRoute,
  AdminShellDashboardRoute: AdminShellDashboardRoute,
  AdminShellSettingsRoute: AdminShellSettingsRoute,
}

const AdminShellRouteRouteWithChildren = AdminShellRouteRoute._addFileChildren(
  AdminShellRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminShellRouteRoute: typeof AdminShellRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminShellRouteRoute: AdminShellRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BookAppointmentRoute: BookAppointmentRoute,
  ContactRoute: ContactRoute,
  DoctorsRoute: DoctorsRoute,
  GalleryRoute: GalleryRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TreatmentsRoute: TreatmentsRoute,
  ConcernsSlugRoute: ConcernsSlugRoute,
  ConcernsIndexRoute: ConcernsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
